[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PeculiarPlaces"
version = "0.1.0"
dependencies = [
    "flask==2.3.3",
    "flask-restful",
    "flask-sqlalchemy",
    "flask-caching",
    "flask-api-key",
    "pytest",
    "pytest-flask",
    "factory-boy",
    "pytest-cov",
]

[tool.setuptools]
packages = ["PeculiarPlaces"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--tb=short --strict-markers"
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
]
